inherit_from: .rubocop_todo.yml

Encoding:
  Enabled: false

Metrics/ClassLength:
  CountComments: false

Metrics/MethodLength:
  CountComments: false

AllCops:
  Exclude:
    - structured_text_renderer.gemspec
    - spec/**/*
    - Guardfile
    - Gemfile
    - Rakefile

Metrics/ClassLength:
  Max: 250

Style/MutableConstant:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'only_fail'
