require_relative './block_renderers/entry_block_renderer'
require_relative './block_renderers/heading_one_renderer'
require_relative './block_renderers/heading_two_renderer'
require_relative './block_renderers/heading_three_renderer'
require_relative './block_renderers/heading_four_renderer'
require_relative './block_renderers/heading_five_renderer'
require_relative './block_renderers/heading_six_renderer'
require_relative './block_renderers/paragraph_renderer'
