require_relative './text_renderers/text_renderer'
require_relative './text_renderers/bold_renderer'
require_relative './text_renderers/code_renderer'
require_relative './text_renderers/italic_renderer'
require_relative './text_renderers/underline_renderer'
